
# Flick Magnet Server Configuration

[server]

# A name to identify the server
name = "Flick Magnet"

# Preferred video quality: 480, 720, or 1080
preferred_quality = 720

# How many years after a movie is published that it becomes public domain and can be shared
# Adjust this for your local copyright terms: https://en.wikipedia.org/wiki/List_of_countries%27_copyright_lengths
# copyright_length = 75  # US
copyright_length = -2   # disabled

# Old videos are deleted if they are not watched for this many days
# Defaults to number of gigabytes free space
# video_cache_days = 7

# Port to listen for HTTP clients, defaults to a random port
http_port = 42000

# IP to listen for HTTP clients
http_addr = "0.0.0.0"

# Hostname that HTTP clients can connect to, defaults to local network IP
# http_host = "flickmag.net"

# Port to listen for bittorrent, defaults to a random port
# torrent_port = 6881
