
# Flick Magnet Server Configuration

[server]

# A name to identify the server
name = "Flick Magnet"

# Port to listen for HTTP clients, defaults to a random port
http_port = 42000

# IP to listen for HTTP clients
http_addr = "0.0.0.0"

# Hostname that HTTP clients can connect to, defaults to local network IP
# http_host = "flickmag.net"

# Videos are deleted if they are not watched for this many days
# video_cache_days = 7
